5w2h_git/5w2h/Areas/Gestao/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Repository;
using Services;
using Repository.Controle;
using Bussines;
using _5w2h.util;

namespace _5w2h.Areas.Gestão.Controllers
{   
    [Area("Gestão")]
    public class CadastroController : Controller
    {
        private Context _context;
        private FuncionarioService _funcionario;
        
        public CadastroController(Context context)
        {
            _context = context;
            _funcionario = new FuncionarioService(new GenericRepository<Funcionario>(context));
        }


        // GET: CadastroController
        public ActionResult Index()
        {
            List<Funcionario> func = _funcionario.BuscarTodos().OrderBy(f=>f.Codigo).ToList();
            return View(func);
        }

        // GET: CadastroController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CadastroController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CadastroController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Funcionario func, bool novoValor)
        {
            

            if (novoValor == true)
            {
                func.NomeCompleto = "111";
            } else
            {
                func.NomeCompleto = "2222";
            }
            try
            {
                if (_funcionario.Criar(func))
                {
                    Validation<Funcionario>.CopyValidation(ModelState, _funcionario);
                    return RedirectToAction(nameof(Index));
                } else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: CadastroController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CadastroController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CadastroController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CadastroController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

5w2h_git/5w2h/Areas/Gestao/Controllers/testeController.cs
using Microsoft.AspNetCore.Mvc;
using Repository.Controle;
using Repository;
using Services;
using Bussines;

namespace _5w2h.Areas.Gestão.Controllers
{
    [Area("Gestão")]
    public class testeController : Controller
    {
        private readonly ILogger<testeController> _logger;
        private Context _context;
        private QuadroService _quadroService;

        public testeController(Context context, ILogger<testeController> logger)
        {
            _logger = logger;
            _context = context;
            _quadroService = new QuadroService(new QuadroRepository(context));
        }

        public IActionResult Index()
        {
            List<Quadro> quadros = _quadroService.BuscarTodos().OrderBy(q => q.Nome).ToList();
            ViewBag.quadros = quadros;
            return View();
        }
    }
}

5w2h_git/5w2h/Areas/Gestaoo/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Repository;
using Services;
using Repository.Controle;
using Bussines;
using _5w2h.util;
using System.Numerics;
using System;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace _5w2h.Areas.Gestão.Controllers
{   
    [Area("Gestaoo")]
    public class CadastroController : Controller
    {
        private Context _context;
        private FuncionarioService _funcionario;
        private LoginService _login;

        public CadastroController(Context context)
        {
            _context = context;
            _funcionario = new FuncionarioService(new GenericRepository<Funcionario>(context));
            _login = new LoginService(new GenericRepository<Login>(context));
        }


        // GET: CadastroController
        public ActionResult Index()
        {
            List<Funcionario> func = _funcionario.BuscarTodos().Where(f => f.Ativo != -1).OrderBy(f=>f.Codigo).ToList();
            return View(func);
        }

        public ActionResult Ativar()
        {
            List<Funcionario> funcInativos = _funcionario.BuscarTodos().Where(f => f.Ativo == -1).OrderBy(f => f.Codigo).ToList();
            return View(funcInativos);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ativar(int id, IFormCollection collection)
        {
            try
            {
                if (_funcionario.Ativar(id))
                {
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    Validation<Funcionario>.CopyValidation(ModelState, _funcionario);
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: CadastroController/Details/5
        public ActionResult Details(int id)
        {
            Funcionario fDetalhe = _funcionario.BuscarTodos().Where(f => f.Codigo == id).FirstOrDefault();
            Login loginFunc = _login.BuscarTodos().Where(l => l.CodigoFuncionario == fDetalhe.Codigo).FirstOrDefault();
            ViewBag.loginDetlhe = loginFunc;
            return View(fDetalhe);
        }

        // GET: CadastroController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CadastroController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Funcionario func, bool Gestor, bool Ativo, string Email, string Senha)
        {
            

            if (Gestor == true)
            {
                func.Gestor = 1;
            } else
            {
                func.Gestor = 0;    
            }

            if (Ativo == true)
            {
                func.Ativo = 1;

            }
            else
            {
                func.Ativo = -1;
            }


            try
            {

                if (_funcionario.Criar(func))
                {
                    
                    try
                    {
                        if (Email != "" && Senha != "")
                        {
                            Login l = new Login();
                            l.Email = Email;
                            l.Senha = Senha;
                            l.CodigoFuncionario = func.Codigo;

                            _login.Criar(l);

                        }
                        Validation<Funcionario>.CopyValidation(ModelState, _funcionario);
                        return RedirectToAction(nameof(Index));
                    }
                    catch
                    {
                        Validation<Funcionario>.CopyValidation(ModelState, _funcionario);
                        return RedirectToAction(nameof(Index));
                    }
                    

                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }


        }

        // GET: CadastroController/Edit/5
        public ActionResult Edit(int id)
        {
            Funcionario updateFunc = _funcionario.BuscarTodos().Where(f => f.Codigo == id).FirstOrDefault();
            ViewBag.updateF = updateFunc;
            Login loginFunc = _login.BuscarTodos().Where(l=>l.CodigoFuncionario == updateFunc.Codigo).FirstOrDefault();
            ViewBag.loginFunc = loginFunc;
            return View();
        }

        // POST: CadastroController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Funcionario funcEdit, int id, bool Gestor, bool Ativo, string Email, string Senha)
        {
            
            Funcionario testeF = _funcionario.BuscarTodos().Where(f=>f.Codigo == id).FirstOrDefault();

            #region Gestor/Ativo
                if (Gestor == true)
                {
                    funcEdit.Gestor = 1;
                }
                else
                {
                    funcEdit.Gestor = 0;
                }

                if (Ativo == true)
                {
                    funcEdit.Ativo = 0;

                }
                else
                {
                    funcEdit.Ativo = -1;
                }
            #endregion

            Login loginUpdate = _login.BuscarTodos().Where(l=>l.CodigoFuncionario == testeF.Codigo).FirstOrDefault();

            if(loginUpdate == null)
            {
                if (Email != null && Senha != null)
                {

                    Login novol = new Login();
                    novol.Senha = Senha;
                    novol.Email = Email;
                    novol.CodigoFuncionario = testeF.Codigo;
                    _login.Criar(novol);
                }
                

            } else
            {
                if (Email != "" && Senha != "")
                {
                    loginUpdate.Senha = Senha;
                    loginUpdate.Email = Email;
                    _login.Atualizar(loginUpdate);
                }

            }

            if (testeF != null)
            {
                testeF.NomeCompleto = funcEdit.NomeCompleto;
                testeF.CPF = funcEdit.CPF;
                testeF.Ativo = funcEdit.Ativo;
                testeF.Gestor = funcEdit.Gestor;
            }

            try
            {
                if (_funcionario.Atualizar(testeF))
                {
                    return RedirectToAction(nameof(Index));

                }else
                {
                    Validation<Funcionario>.CopyValidation(ModelState, _funcionario);
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: CadastroController/Delete/5
        public ActionResult Delete(int id)
        {
            Funcionario funcInativar = _funcionario.BuscarTodos().Where(f => f.Codigo == id).FirstOrDefault();

            return View(funcInativar);
        }

        // POST: CadastroController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                if (_funcionario.Inativar(id))
                {
                    return RedirectToAction(nameof(Index));

                }
                else
                {
                    Validation<Funcionario>.CopyValidation(ModelState, _funcionario);
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

5w2h_git/5w2h/Areas/Gestaoo/Views/Cadastro/Delete.cshtml
@model Bussines.Funcionario

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Gestaoo/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Funcionario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gestor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gestor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

5w2h_git/5w2h/Areas/Gestaoo/Views/Cadastro/Details.cshtml
@model Bussines.Funcionario

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Gestaoo/Views/Shared/_Layout.cshtml";

    Bussines.Login l = ViewBag.loginDetlhe;
}
   
<!DOCTYPE html>
<html lang="en">
<head >
    <meta charset="UTF-8">
    
    <title>5W2H Board</title>

    
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    

    
    
    
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>  
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/cadastro.css">
    <link rel="stylesheet" href="~/css/modalPerfil.css">
    <link rel="icon" type="image/png" href="~/img/iconeAba.png" sizes="5x5">
</head>
<body  >
    
   

    <div class="header">
        <img src="~/img/logoCurto.png" alt="">
        
        
        <div class="novoQuadroBotao">
            <a asp-controller="teste" asp-action="Index" class="primary">Voltar</a>
            <img src="~/img/logopng.png" alt="" class="logoHeader" onclick="openPerfil()">
        </div>
    </div>



    <div id="boxCadastro">
        <div class="box">
            <div class="head">
                <span>Cadastro</span>

                
            </div>

            <form asp-action="Create" class="form">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NomeCompleto" class="control-label">Nome Completo</label>
                    <input asp-for="NomeCompleto" class="form-control" type="text" value="@Model.NomeCompleto" disabled />
                    <span asp-validation-for="NomeCompleto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">E-mail</label>
                    
                    @if (l != null)
                    {

                        <input class="form-control" type="text" name="Email" value="@l.Email" disabled/>
                    }
                    else
                    {
                        <input class="form-control" type="text" name="Email" disabled />
                    }
                </div>
                <div class="form-group">
                    <label asp-for="CPF" class="control-label">CPF</label>
                    <input asp-for="CPF" class="form-control" type="text" value="@Model.CPF" disabled />
                    <span asp-validation-for="CPF" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Senha Inicial</label>
                    @if(l != null)
                    {

                        <input class="form-control" value="@l.Senha" type="text" name="Senha"  />
                    } else
                    {
                        <input class="form-control" type="text" name="Senha" />
                    }

                </div>




                <div class="form-group" style="display: flex; align-items: center;">
                    <label asp-for="Gestor" class="control-label" name="Gestor"></label>

                    @Html.Hidden("Gestor",  false )
                    @if (@Model.Gestor == 1)
                    {

                        <input type="checkbox" id="inputTrocarGestor" checked  />
                    }
                    else
                    {
                        <input type="checkbox" id="inputTrocarGestor"  />
                    }
                </div>
                <div class="form-group" style="display: flex; align-items: center;">
                    <label asp-for="Ativo" class="control-label"></label>

                    @Html.Hidden("Ativo", false)
                    @if (@Model.Ativo == 1)
                    {

                        <input type="checkbox" id="inputTrocarAtivo" checked disabled />
                    }
                    else
                    {
                        <input type="checkbox" id="inputTrocarAtivo" disabled />
                    }

                </div>
                
                <div class="footer">
                    
                    <button class="primary" value="Criar" asp-controller="Cadastro" asp-action="Index">Voltar</button>
                </div>
            </form>

        </div>
    </div>

    
    <div id="modalPerfilCadastro">
        <div class="box">
            
            <img id="fotoCapa" src="./img/logopng.png" alt="" class="fotoTrocada">
            
            
          
            <div class="perfil-group">

                <a href="#" >
                    <ion-icon  name="image-outline" class="iconePerfil"></ion-icon>  
                    <input type="file"  id="upload" onchange="showThumbnail(this)">
                    <label for="upload" style="cursor: pointer">Trocar Foto</label> 
                </a>
            </div>
            <hr >
            <div class="perfil-group">

                <a href="#">
                    <ion-icon name="lock-closed-outline" class="iconePerfil"></ion-icon>
                    <span>Alterar Senha</span>
                </a>
            </div>
            <hr >
            <div class="perfil-group">

                <a href="./login.html">
                    <ion-icon name="exit-outline" class="iconePerfil"></ion-icon>
                    <span>Deslogar</span>
                </a>
            </div>
                


        </div>
    </div>

    <div id="modalConsulta">
        <div class="box">
            <div class="head">
                <span class="consultaSpan">Consultar Funcionários</span>
                <button onclick="fecharModalConsulta()" class="closeConsulta">X</button>
            </div>
            <div class="form" style="padding: 14px;">
                <div class="apenasAtivos">
                    <input type="checkbox" id="usuariosAtivos" placeholder="" checked="true"/>
                    <label for="usuariosAtivos">Apenas Ativos</label> 
                </div>
                <div class="pesquisar">
                    <input type="text" class="pesquisarConsulta" placeholder="Pesquisar">
                    <ion-icon name="search-outline"></ion-icon>
                </div>
                <div class="listaFuncionario">
                    <ul style="list-style-type: none;
                    /* padding-left: 0px; */
                    background: #DDD;
                    border: 1px solid #333;
                    border-top: 1px solid #a59898;
                    border-radius: 0 0 10px 10px;
                ">
                        <li class="funcionario" onclick="consultaFuncionario('Karolina Fernanda')" id="ativo">Karolina Fernanda <span class="ativoSpan">Ativo</span></li>
                        <li class="funcionario" onclick="consultaFuncionario('Kate Silva')" id="ativo">Kate Silva<span class="ativoSpan">Ativo</span></li>
                        <li class="funcionario" onclick="consultaFuncionario('Gustavo Bozo')" id="inativo">Gustavo Bozo <span class="inativoSpan">Inativo</span></li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        
        $(document).ready(function () {
            $('#inputTrocarGestor').change(function () {
                $('#Gestor').val(this.checked); 

            });

            $('#inputTrocarAtivo').change(function () {
                $('#Ativo').val(this.checked);
                
            });
        });

        
    </script>
</body>
</html>
    

5w2h_git/5w2h/Areas/Gestaoo/Views/Cadastro/Index.cshtml
@model IEnumerable<Bussines.Funcionario>
@using _5w2h.Areas.Gestão.Controllers

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Gestaoo/Views/Shared/_Layout.cshtml";
    
}

<!DOCTYPE html>
<html lang="en">
<head >
    <meta charset="UTF-8">
    
    <title>5W2H Board</title>

    
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    
    
    
    
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>  
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/cadastro.css">
    <link rel="stylesheet" href="~/css/modalPerfil.css">
    <link rel="icon" type="image/png" href="~/img/iconeAba.png" sizes="5x5">
</head>
<body>
    
   

    <div class="header">
        <img src="~/img/logoCurto.png" alt="">
        
        
        <div class="novoQuadroBotao">
            <a asp-action="Index" asp-controller="teste" class="primary">Voltar</a>
            <img src="~/img/logopng.png" alt="" class="logoHeader" onclick="openPerfil()">
        </div>
    </div>


    <div class="containers">
        <div class="lista_funcionario">
            <div class="lista_header" >
                <h1>Funcionários cadastrados: </h1>

                <div class="d-flex gap-2">

                <p class="create_func">
                    <a asp-action="Create">Cadastrar Novo</a>
                </p>
                <p class="create_func">
                    <a asp-action="Ativar">Ativar Funcionário</a>
                </p>
                </div>
            </div>
            <table class="table_func">
                <thead >
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Codigo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CPF)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NomeCompleto)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Gestor)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Ativo)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Codigo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CPF)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NomeCompleto)
                            </td>
                            <td>
                                @if(item.Gestor == 1)
                                {

                                    @Html.DisplayName("Sim");
                                } else
                                {
                                    @Html.DisplayName("Não");
                                }
                            </td>
                            <td>

                                @if (item.Ativo == 0)
                                {

                                    @Html.DisplayName("Sim");
                                }
                                else
                                {
                                    @Html.DisplayName("Não");
                                }
                                
                                
                            </td>
                            <td>
                                @Html.ActionLink("Editar", "Edit", new { id=item.Codigo }) |
                                @Html.ActionLink("Consultar", "Details", new { id=item.Codigo  }) |
                                

                                <a data-bs-toggle="modal" data-bs-target="#exampleModal">
                                    Inativar
                                </a>

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                Deseja mesmo inativar o funcionário @item.NomeCompleto ?
                                            </div>
                                            <div class="modal-footer">
                                                @using (Html.BeginForm("Delete", "Cadastro", new { id = item.Codigo }, FormMethod.Post))
                                                {
                                                    @Html.AntiForgeryToken()
                                                    <input type="submit" value="Excluir" class="btn btn-danger" />
                                                }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            
                        </tr>
                    }
                    
                </tbody>
            </table>
        </div>
        
    </div>

    


    
    <div id="modalPerfilCadastro">
        <div class="box">
            
            <img id="fotoCapa" src="./img/logopng.png" alt="" class="fotoTrocada">
            
            
          
            <div class="perfil-group">

                <a href="#" >
                    <ion-icon  name="image-outline" class="iconePerfil"></ion-icon>  
                    <input type="file"  id="upload" onchange="showThumbnail(this)">
                    <label for="upload" style="cursor: pointer">Trocar Foto</label> 
                </a>
            </div>
            <hr >
            <div class="perfil-group">

                <a href="#">
                    <ion-icon name="lock-closed-outline" class="iconePerfil"></ion-icon>
                    <span>Alterar Senha</span>
                </a>
            </div>
            <hr >
            <div class="perfil-group">

                <a href="./login.html">
                    <ion-icon name="exit-outline" class="iconePerfil"></ion-icon>
                    <span>Deslogar</span>
                </a>
            </div>
                


        </div>
    </div>

    
    
    <script src="~/js/quadro.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" ></script>
</body>
</html>